/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
USE NFE
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NFe
	DROP CONSTRAINT FK_NFe_Lote
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NFeCloudQueue
	DROP CONSTRAINT FK_NFeCloudQueue_NFe
GO
ALTER TABLE dbo.NFeItens
	DROP CONSTRAINT FK_NFeItens_NFe
GO
ALTER TABLE dbo.Evento
	DROP CONSTRAINT FK_Evento_NFe
GO
ALTER TABLE dbo.NFe ADD CONSTRAINT
	FK_NFe_Lote FOREIGN KEY
	(
	IdLote
	) REFERENCES dbo.Lote
	(
	IdLote
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NFeItens ADD CONSTRAINT
	FK_NFeItens_NFe FOREIGN KEY
	(
	IdInternoNFe
	) REFERENCES dbo.NFe
	(
	IdInternoNFe
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NFeCloudQueue ADD CONSTRAINT
	FK_NFeCloudQueue_NFe FOREIGN KEY
	(
	IdInternoNFe
	) REFERENCES dbo.NFe
	(
	IdInternoNFe
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Evento ADD CONSTRAINT
	FK_Evento_NFe FOREIGN KEY
	(
	IdInternoNFe
	) REFERENCES dbo.NFe
	(
	IdInternoNFe
	) ON UPDATE  NO ACTION 
	 ON DELETE  SET NULL
	
GO
COMMIT
